apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-{{ .Values.environment }}
  namespace: {{ .Values.namespacePrefix }}-{{ .Values.environment }}
  labels:
    # app: {{ .Values.appName }}-{{ .Values.environment }}
    workload.user.cattle.io/workloadselector: {{ include "rancher.selector" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      # app: {{ .Values.appName }}-{{ .Values.environment }}
      workload.user.cattle.io/workloadselector: {{ include "rancher.selector" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate      
  template:
    metadata:
      labels:
        # app: {{ .Values.appName }}-{{ .Values.environment }}
        workload.user.cattle.io/workloadselector: {{ include "rancher.selector" . }}
    spec:
      containers:
        - name: {{ .Values.appName }}-{{ .Values.environment }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - node
          - express.js          
